### ISSUE TITLE
ircWhois results in Notice and Warning

### ISSUE THREAD

**Issue by hashworks** [phergie/phergie-irc-client-react#27]
```php
$queue->ircWhois('', 'hashworks');
```

```
PHP Warning:  Missing argument 2 for Phergie\Irc\Client\React\WriteStream::ircWhois() in phergie/phergie-irc-client-react/src/WriteStream.php on line 434
PHP Notice:  Undefined variable: nickmasks in phergie-irc-client-react/src/WriteStream.php on line 436
```

**Comment by elazar** [comment]
This appears to be an issue with the `$server

**Comment by hashworks** [comment]
According to https://tools.ietf.org/html/rfc2812#section-3.6.2 you don't have to set a target.

**Comment by elazar** [comment]
Correct. This is an issue in both `WriteStream->ircWhois()` and in [`GeneratorInterface`](https://github.com/phergie/phergie-irc-generator/blob/402a9c9dc341a8d5902faae11a9459ed41a59767/src/GeneratorInterface.php#L303) and its [`Generator`](https://github.com/phergie/phergie-irc-generator/blob/402a9c9dc341a8d5902faae11a9459ed41a59767/src/Generator.php#L387) implementation. Filing an issue against that repo as well.

**Comment by elazar** [comment]
So, there are two ways to approach addressing this:

1. Maintain the current parameter order of `ircWhois()`, make the `$nickmasks` parameter optional, and require the method implementation to handle swapping the values of `$server` and `$nickmasks` if only a single parameter value is specified when `ircWhois()` is called. This maintains backward compatibility, but requires a bit more of the implementation and makes it slightly less clean.
2. Swap the parameter order of `ircWhois()` such that `$server` is last and as such can be defaulted to `null`. `getIrcMessage()` already handles filtering out `null` values. This means a cleaner implementation, but breaks backward compatibility because calls to the method have to change their parameter order.

Thoughts? @hashworks?

**Comment by Renegade334** [comment]
Option 1 is closer to the way it's implemented at a server level.

There is the [Third Option™](http://tvtropes.org/pmwiki/pmwiki.php/Main/TakeAThirdOption) which would be a filthy dose of `func_get_args()`...

**Comment by hashworks** [comment]
I'll answer next Sunday. I'm drunk till Saturday.

**Comment by elazar** [comment]
@hashworks Fair enough

@Renegade334 I'd prefer to keep the solution as clean and simple as possible. Much as I don't care for the two options I've detailed above, they do meet both criteria.

**Comment by Renegade334** [comment]
Agreed. I just enjoy throwing spanners.

**Comment by elazar** [comment]
@stil Want to throw your hat in the ring on how this should be resolved? [Your affected code.](https://github.com/stil/phoebe/blob/7bef21bca472c01556780d1fc7e32ccc7781480d/src/Plugin/Whois/WhoisPlugin.php#L33)

**Comment by elazar** [comment]
Assuming we change the argument order, [`EventQueue`](https://github.com/phergie/phergie-irc-bot-react/blob/aef6a00739c221bc2442405cd6454fa6bb264b54/src/EventQueue.php#L478) in the bot repo will be affected as well.

**Comment by Renegade334** [comment]
I personally don't think that any write command should require its parameters to specified in a different order to how they will be sent.

**Comment by elazar** [comment]
@Renegade334 I believe there's only [one other case](https://github.com/phergie/phergie-irc-generator/blob/cf8b2ea51fb4e35b55f9cced432debdc12984190/src/Generator.php#L274-276) where we've done just that, because of parameter order coupled with optionality.

**Comment by hashworks** [comment]
Is there any clean PHPDoc definition available for swapable variables? However it agitates me to do something like that in PHP. If we can change the parameter order in one go we should do it, it doesn't affect a ton of code. Additionally there are only a few people who use the ircWhois command.

My vote goes for solution number 2.

**Comment by stil** [comment]
As for me, I also would keep it clean as possible. Breaking backwards compatibility is ok if it's reflected in version change.

**Comment by elazar** [comment]
Question: does the affected `ircWhois()` method, as it stands now, work correctly under any circumstances? If not, we wouldn't even necessarily need to call it a BC break; it's a bug.

**Comment by hashworks** [comment]
@elazar: It works correctly. The issue is just about the warning, the whois works just fine.

**Comment by elazar** [comment]
@Renegade334 Sounds like the popular vote is option 2. Any thoughts before we proceed on that route?

**Comment by Renegade334** [comment]
Nope, I agree with keeping it consistent if there are other cases that already use reversed parameter order where the first parameter is optional.
