### ISSUE TITLE
QUIT handler in WriteStream results in the socket being closed before writing the QUIT command

### ISSUE THREAD

**Issue by Renegade334** [phergie/phergie-irc-client-react#32]
The quit handler in `WriteStream` intends to write the command to the socket and then close the stream as follows:

``` php
$this->emit('data', array($msg));
$this->close();
```

On calling `$this->close()`, the `'end'` event is thrown and the closure returned by `Client::getEndCallback` will mop up and close the socket stream. This occurs before the socket stream handles the send buffer, so the quit command is never sent to the server, and other IRC users will see a disconnect message saying that the client closed the socket, rather than seeing the intended quit message.

There needs to be some mechanism whereby the socket stream's send buffer is flushed before closing it.

**Comment by Renegade334** [comment]
Could possibly just be a case of changing `$stream->close()` to `$stream->end()` in `Client::getEndCallback`. Needs to be tested to see if that fails gracefully if the socket is a timed-out zombie, but it should work.

**Comment by Renegade334** [comment]
Appears to work. I set up an ircQuit timer, then severed the physical network connection before it was called. `$stream->end()` still resulted in the stream being closed.

**Comment by elazar** [comment]
@Renegade334 Awesome! Yeah, think this was just an oversight on my part. PR? :)

**Comment by Renegade334** [comment]
Do the read and write streams for the connection need to be explicitly closed as well once the socket stream closes? At the moment, they're not, and I think they probably should be.

**Comment by elazar** [comment]
I believe `React\Stream\Stream` [handles that](https://github.com/reactphp/stream/blob/56c627a7bb19c58d85ed757efc2163810443e671/src/Stream.php#L132-134) when it's closed; see its `end()` and `close()` methods.

**Comment by Renegade334** [comment]
I'm referring to the `Client\ReadStream` and `Client\WriteStream` objects, rather than the socket stream resource.

**Comment by elazar** [comment]
Ah, I think I see what you mean: `close()` is called on `WriteStream` within its `ircQuit()` method, but I don't think `close()` is ever called on the `ReadStream` instance. Maybe `getEndCallback()` should be modified to accept both streams and call `end()` on both?

**Comment by elazar** [comment]
Merged #34.
