### ISSUE TITLE
Refactor to use new bot event queue handling

### ISSUE THREAD

**Issue by elazar** [phergie/phergie-irc-client-react#36]
See phergie/phergie-irc-bot-react#19. Update `Client` to use this functionality rather than [rolling its own](https://github.com/phergie/phergie-irc-client-react/blob/94f131905986f542342199672ce2946f60d893e0/src/Client.php#L284-289). Note that this should include requiring bot:~1.2 in `composer.json`.

Related: phergie/phergie-irc-connection#5

**Comment by Renegade334** [comment]
Addressed by #35.

**Comment by elazar** [comment]
Confirmed. Closing.
