### ISSUE TITLE
Internal processing

### ISSUE THREAD

**Issue by Renegade334** [phergie/phergie-irc-client-react#40]
I am working on a branch under [`Renegade334@devel-internal-processing`](https://github.com/Renegade334/phergie-irc-client-react/tree/devel-internal-processing) that would give the client some input processing functionality in order to store or modify connection-specific data.

Examples of internal processing that the client absolutely should handle:
* Calling `Connection::setNickname()` on receiving a `NICK` command from the server that corresponds to the connection
* Responding to server `PING` messages

Examples that the client could handle:
* Parsing `RPL_ISUPPORT` into a data array of server-supported parameters, plus mode and prefix maps
* Parsing `JOIN`, `MODE`, `PART`, `KICK`, `QUIT` and `RPL_NAMREPLY` messages to compile and maintain internal channel lists
* Parsing `MODE` messages to maintain a record of the client user's current user modes

**Comment by elazar** [comment]
Would the last two items negate the need for https://github.com/Renegade334/phergie-irc-plugin-react-chanmodes ?

**Comment by Renegade334** [comment]
Yes. Also, Pong functionality should definitely be included here.

**Comment by elazar** [comment]
Also, I'm a little concerned at the description of this change. The client was designed specifically to be relatively simple, low-level, and lightweight, and the bot to build on top of that using plugins. I'm afraid of losing the simplicity of the client if too much logic is added at that level. Can you outline how you plan to implement these changes?

**Comment by Renegade334** [comment]
The objective would be to provide core functionality - that functionality that should be present in all cases, like responding to server pings or updating the connection's nickname - as part of the client. I've added an example to the branch.

**Comment by elazar** [comment]
How would any parsed data be made accessible to non-core code?

**Comment by Renegade334** [comment]
Through the connection data scheme. Example: 7de37f79b718716cd210fa494bcca8ca2f3ba052

The same scheme could be used by plugins to provide non-essential functionality that isn't handled by the client. For example, if it's decided that channel lists shouldn't be handled by the client, a plugin could maintain the channel lists within the connection instances, which could then be accessed at liberty by any other plugins that want to access that data.

**Comment by elazar** [comment]
Fair enough. Feel free to proceed.

**Comment by svpernova09** [comment]
resolved via #42
