### ISSUE TITLE
How to disconnect an active connection?

### ISSUE THREAD

**Issue by fieg** [phergie/phergie-irc-client-react#47]
There is of course the `addConnection`, but no `removeConnection` or something similar. So how can one disconnect from an irc server?

**Comment by elazar** [comment]
Call `ircQuit()` on the `$write` parameter sent to the event callback.

**Comment by fieg** [comment]
Just found [PhergieKeepAlive](https://github.com/nfauchelle/PhergieKeepAlive/blob/master/src/Plugin.php) where they indeed do `ircQuit`. Felt a bit weird to me at first, as it seems a lot more logical to me to call some method on the client to disconnect. But if it works, it's good enough for me :+1: 

Thanks for the quick response.
